version: '3'
services:
  hexo:
    image: spurin/hexo
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - .ssh:/root/.ssh  
    environment:
      - GIT_USER="Anson Chiu"
      - GIT_EMAIL="e314520513@gmail.com"      
    command: >
      /bin/bash -c "
      tail -f /dev/null;
      "      
            
